---
- name: this play book install httpd and apache2
  hosts: all
  become: true
<<<<<<< HEAD
  tasks:  
=======
  tasks:
>>>>>>> 541e36a316d6432039105f3f1a5850b4d0b73fb0
  - name: Install Apache web server
    yum:
     name: httpd
     state: installed
    when: ansible_os_family == "RedHat"

  - name: stated web server
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: install apache2 server
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: start apache2
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"

  - name: copy the index file
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
