---
- name: This playbook install httpd services
  hosts: dbservers
  become: true
  tasks:
  - name: Install Apache web server
    apt: 
     name: apache2
     state: present
  - name: stated web server
    service:
      name: apache2
      state: started
