---
- name: This playbook install httpd services
  hosts: webservers
  become: true
  tasks:
  - name: Install Apache web server
    yum:
     name: httpd
     state: installed
  - name: stated web server
    service:
      name: httpd
      state: started

