---
- name: this play book install webserver
  hosts: all
  become: true
  tasks:

  - name: install packages
    yum:
     name: httpd
     state: installed
    when: ansible_os_family == "RedHat"
    notify: start apache

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  handlers:
  - name: start apache
    yum:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: start apache2
    apt:
      name: apache2
      state: started
    when: ansble_os_familu == "Debian"
