---
- name: playbook is uninstall httpd and apache2 server
  hosts: all
  become: true
  tasks:
  - name: stop the httpd service
    service:
     name: httpd
     state: stopped
    when: ansible_os_family == "RedHat"

  - name: removed httpd service
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: stop the apache2 service
    service:
     name: apache2
     state: stopped
    when: ansible_os_family == "Debian"

  - name: Uninstall apache2 service
    apt:
     name: apache2
     state: absent
    when: ansible_os_family == "Debian"
