---
- name: This playbook install httpd services
  hosts: webservers
  become: true
  tasks:
  - name: stop apache web server
    service: 
     name: httpd
     state: stopped

  - name: uninstall apache web server
    yum:
     name: unistalled
     state: removed
