---
- name: This playbook uninstall httpd services
  hosts: dbservers
  become: true
  tasks:
  - name: stop apache2 server
    service:
     name: apache2
     state: stopped

  - name: uninstall apache2
    apt:
     name: apache2
     autoremove: tes
       
